#:import Snackbar kivymd.uix.snackbar.Snackbar
Gereciadordetelas:
    MenuScreen:
        name:'menu'
    Votacao:
        name:'votacao'
    Cadastro:
        name:'cadastro'
    Resultado:
        name:'resultado'

<MenuScreen>:
    ScrollView:
        MDFloatLayout:
            FitImage:
                source:"img/pexels-element-digital-1550337.jpg"
                pos_hint:{"center_x":.5,"center_y":.9}
                size_hint: .3, .3
            MDRaisedButton:
                pos_hint:{"center_x": 0.5,"center_y": 0.6}
                size_hint:(0.5,0.1)
                text:"Votação"
                on_release:
                    app.root.current = 'votacao'
                    root.manager.transition.direction = 'left'
            MDRaisedButton:
                pos_hint:{"center_x": 0.5,"center_y": 0.4}
                size_hint:(0.5,0.1)
                text:"Cadastro"
                on_release:
                    app.root.current = 'cadastro'
                    root.manager.transition.direction = 'left'
            MDRaisedButton:
                pos_hint:{"center_x": 0.5,"center_y": 0.2}
                size_hint:(0.5,0.1)
                text:"Resultado"
                on_release:
                    app.root.current = 'resultado'
                    root.manager.transition.direction = 'left'
            MDIconButton:
                icon: "language-python"
                pos_hint: {"center_x": .98, "center_y": 0.03}
                on_release:
                    root.switch_theme_style()
<Votacao>:
    MDFloatLayout:
        MDGridLayout:
            id:grid
            cols:6
            spacing:30
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True

        MDFloatLayout:
            MDFillRoundFlatButton:
                text:"Votar"
                pos_hint:{'center_x':.06,'center_y':.3}
                on_press:
                    Snackbar(text="Seu voto foi Computado").open()
                    root.eleicao()
            MDFillRoundFlatButton:
                text:"Votar"
                pos_hint:{'center_x':.23,'center_y':.3}
                on_press:
                    Snackbar(text="Seu voto foi Computado").open()
                    root.eleicao1()
            MDFillRoundFlatButton:
                text:"Votar"
                pos_hint:{'center_x':.39,'center_y':.3}
                on_press:
                    Snackbar(text="Seu voto foi Computado").open()
                    root.eleicao2()
            MDFillRoundFlatButton:
                text:"Votar"
                pos_hint:{'center_x':.55,'center_y':.3}
                on_press:
                    Snackbar(text="Seu voto foi Computado").open()
                    root.eleicao3()
            MDFillRoundFlatButton:
                text:"Votar"
                pos_hint:{'center_x':.71,'center_y':.3}
                on_press:
                    Snackbar(text="Seu voto foi Computado").open()
                    root.eleicao4()
            MDFillRoundFlatButton:
                text:"Votar"
                pos_hint:{'center_x':.86,'center_y':.3}
                on_press:
                    Snackbar(text="Seu voto foi Computado").open()
                    root.eleicao5()
            MDRaisedButton:
                id:btn
                text:"iniciar"
                halign:"center"
                pos_hint:{'center_x':.97,'center_y':.9}
                on_press:
                    root.fetchall()
            MDBottomAppBar:
                md_bg_color: 0, 0, 1, 1

                MDTopAppBar:
                    title: "votacao"
                    icon: "arrow-left-circle"
                    type: "bottom"
                    icon_color: 0, 0, 1, 1
                    mode:'end'
                    on_action_button:
                        app.root.current = "menu"
                        root.manager.transition.direction = 'right'

<Cadastro>:
    ScrollView:
        BoxLayout:
            spacing:10
            orientation:'vertical'
            MDTextField:
                id:nome
                size_hint_x:0.4
                pos_hint:{"center_x": 0.5,"center_y": 0.}
                hint_text: "nome"
                mode: "rectangle"
            MDTextField:
                id:idade
                size_hint_x:0.4
                pos_hint:{"center_x": 0.5,"center_y": 0.8}
                hint_text: "Idade"
                mode: "rectangle"
            MDTextField:
                id:descricao
                size_hint_x:0.4
                pos_hint:{"center_x": 0.5,"center_y": 0.8}
                hint_text: "descrição"
                multiline:  True
                mode: "rectangle"
            MDFillRoundFlatButton:
                id:cadastrar
                pos_hint:{"center_x": 0.5,"center_y": 0.5}
                text:"Cadastrar"
                on_release:
                    root.submit()

            MDBottomAppBar:
                md_bg_color: 0, 0, 1, 1
                MDTopAppBar:
                    title: "Cadastro de candidatos"
                    icon: "arrow-left-circle"
                    type: "bottom"
                    icon_color: 0, 0, 1, 1
                    mode:'end'
                    on_action_button:
                        app.root.current = "menu"
                        root.manager.transition.direction = 'right'






<Resultado>:
    ScrollView:

        MDFloatLayout:
            id:resultado
            MDLabel:
                id:nomer
                text:""
                halign:"center"

            MDRaisedButton:
                text:"resultado"
                pos_hint:{"center_x":.2,"center_y":.5}
                on_press:
                    root.resultados()
            MDBottomAppBar:
                md_bg_color: 0, 0, 1, 1
                MDTopAppBar:
                    title: "Resultados"
                    icon: "arrow-left-circle"
                    type: "bottom"
                    icon_color: 0, 0, 1, 1
                    mode:'end'
                    on_action_button:
                        app.root.current = "menu"
                        root.manager.transition.direction = 'right'



